/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Window */

#ifndef _Included_main_Window
#define _Included_main_Window
#ifdef __cplusplus
extern "C" {
#endif
#undef main_Window_FOCUS_TRAVERSABLE_UNKNOWN
#define main_Window_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef main_Window_FOCUS_TRAVERSABLE_DEFAULT
#define main_Window_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef main_Window_FOCUS_TRAVERSABLE_SET
#define main_Window_FOCUS_TRAVERSABLE_SET 2L
#undef main_Window_TOP_ALIGNMENT
#define main_Window_TOP_ALIGNMENT 0.0f
#undef main_Window_CENTER_ALIGNMENT
#define main_Window_CENTER_ALIGNMENT 0.5f
#undef main_Window_BOTTOM_ALIGNMENT
#define main_Window_BOTTOM_ALIGNMENT 1.0f
#undef main_Window_LEFT_ALIGNMENT
#define main_Window_LEFT_ALIGNMENT 0.0f
#undef main_Window_RIGHT_ALIGNMENT
#define main_Window_RIGHT_ALIGNMENT 1.0f
#undef main_Window_serialVersionUID
#define main_Window_serialVersionUID -7644114512714619750i64
#undef main_Window_serialVersionUID
#define main_Window_serialVersionUID 4613797578919906343i64
#undef main_Window_INCLUDE_SELF
#define main_Window_INCLUDE_SELF 1L
#undef main_Window_SEARCH_HEAVYWEIGHTS
#define main_Window_SEARCH_HEAVYWEIGHTS 1L
#undef main_Window_OPENED
#define main_Window_OPENED 1L
#undef main_Window_serialVersionUID
#define main_Window_serialVersionUID 4497834738069338734i64
#undef main_Window_DEFAULT_CURSOR
#define main_Window_DEFAULT_CURSOR 0L
#undef main_Window_CROSSHAIR_CURSOR
#define main_Window_CROSSHAIR_CURSOR 1L
#undef main_Window_TEXT_CURSOR
#define main_Window_TEXT_CURSOR 2L
#undef main_Window_WAIT_CURSOR
#define main_Window_WAIT_CURSOR 3L
#undef main_Window_SW_RESIZE_CURSOR
#define main_Window_SW_RESIZE_CURSOR 4L
#undef main_Window_SE_RESIZE_CURSOR
#define main_Window_SE_RESIZE_CURSOR 5L
#undef main_Window_NW_RESIZE_CURSOR
#define main_Window_NW_RESIZE_CURSOR 6L
#undef main_Window_NE_RESIZE_CURSOR
#define main_Window_NE_RESIZE_CURSOR 7L
#undef main_Window_N_RESIZE_CURSOR
#define main_Window_N_RESIZE_CURSOR 8L
#undef main_Window_S_RESIZE_CURSOR
#define main_Window_S_RESIZE_CURSOR 9L
#undef main_Window_W_RESIZE_CURSOR
#define main_Window_W_RESIZE_CURSOR 10L
#undef main_Window_E_RESIZE_CURSOR
#define main_Window_E_RESIZE_CURSOR 11L
#undef main_Window_HAND_CURSOR
#define main_Window_HAND_CURSOR 12L
#undef main_Window_MOVE_CURSOR
#define main_Window_MOVE_CURSOR 13L
#undef main_Window_NORMAL
#define main_Window_NORMAL 0L
#undef main_Window_ICONIFIED
#define main_Window_ICONIFIED 1L
#undef main_Window_MAXIMIZED_HORIZ
#define main_Window_MAXIMIZED_HORIZ 2L
#undef main_Window_MAXIMIZED_VERT
#define main_Window_MAXIMIZED_VERT 4L
#undef main_Window_MAXIMIZED_BOTH
#define main_Window_MAXIMIZED_BOTH 6L
#undef main_Window_serialVersionUID
#define main_Window_serialVersionUID 2673458971256075116i64
/*
 * Class:     main_Window
 * Method:    handleClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_main_Window_handleClick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     main_Window
 * Method:    findWhereToPaintOval
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_main_Window_findWhereToPaintOval
  (JNIEnv *, jobject, jobject);

/*
 * Class:     main_Window
 * Method:    addAfterAcepting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_Window_addAfterAcepting
  (JNIEnv *, jobject);

/*
 * Class:     main_Window
 * Method:    checkIfWIN
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_main_Window_checkIfWIN
  (JNIEnv *, jobject);

/*
 * Class:     main_Window
 * Method:    getCurrentColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_Window_getCurrentColor
  (JNIEnv *, jobject);

/*
 * Class:     main_Window
 * Method:    findWhereToPaintColumnMark
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_main_Window_findWhereToPaintColumnMark
  (JNIEnv *, jobject, jobject);

/*
 * Class:     main_Window
 * Method:    changeTheColumn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_Window_changeTheColumn
  (JNIEnv *, jobject, jint);

/*
 * Class:     main_Window
 * Method:    clearBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_Window_clearBoard
  (JNIEnv *, jobject);

/*
 * Class:     main_Window
 * Method:    getBoardInTheStringRepresentation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_Window_getBoardInTheStringRepresentation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
