/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Window */

#ifndef _Included_Window
#define _Included_Window
#ifdef __cplusplus
extern "C" {
#endif
#undef Window_FOCUS_TRAVERSABLE_UNKNOWN
#define Window_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Window_FOCUS_TRAVERSABLE_DEFAULT
#define Window_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Window_FOCUS_TRAVERSABLE_SET
#define Window_FOCUS_TRAVERSABLE_SET 2L
#undef Window_TOP_ALIGNMENT
#define Window_TOP_ALIGNMENT 0.0f
#undef Window_CENTER_ALIGNMENT
#define Window_CENTER_ALIGNMENT 0.5f
#undef Window_BOTTOM_ALIGNMENT
#define Window_BOTTOM_ALIGNMENT 1.0f
#undef Window_LEFT_ALIGNMENT
#define Window_LEFT_ALIGNMENT 0.0f
#undef Window_RIGHT_ALIGNMENT
#define Window_RIGHT_ALIGNMENT 1.0f
#undef Window_serialVersionUID
#define Window_serialVersionUID -7644114512714619750i64
#undef Window_serialVersionUID
#define Window_serialVersionUID 4613797578919906343i64
#undef Window_INCLUDE_SELF
#define Window_INCLUDE_SELF 1L
#undef Window_SEARCH_HEAVYWEIGHTS
#define Window_SEARCH_HEAVYWEIGHTS 1L
#undef Window_OPENED
#define Window_OPENED 1L
#undef Window_serialVersionUID
#define Window_serialVersionUID 4497834738069338734i64
#undef Window_DEFAULT_CURSOR
#define Window_DEFAULT_CURSOR 0L
#undef Window_CROSSHAIR_CURSOR
#define Window_CROSSHAIR_CURSOR 1L
#undef Window_TEXT_CURSOR
#define Window_TEXT_CURSOR 2L
#undef Window_WAIT_CURSOR
#define Window_WAIT_CURSOR 3L
#undef Window_SW_RESIZE_CURSOR
#define Window_SW_RESIZE_CURSOR 4L
#undef Window_SE_RESIZE_CURSOR
#define Window_SE_RESIZE_CURSOR 5L
#undef Window_NW_RESIZE_CURSOR
#define Window_NW_RESIZE_CURSOR 6L
#undef Window_NE_RESIZE_CURSOR
#define Window_NE_RESIZE_CURSOR 7L
#undef Window_N_RESIZE_CURSOR
#define Window_N_RESIZE_CURSOR 8L
#undef Window_S_RESIZE_CURSOR
#define Window_S_RESIZE_CURSOR 9L
#undef Window_W_RESIZE_CURSOR
#define Window_W_RESIZE_CURSOR 10L
#undef Window_E_RESIZE_CURSOR
#define Window_E_RESIZE_CURSOR 11L
#undef Window_HAND_CURSOR
#define Window_HAND_CURSOR 12L
#undef Window_MOVE_CURSOR
#define Window_MOVE_CURSOR 13L
#undef Window_NORMAL
#define Window_NORMAL 0L
#undef Window_ICONIFIED
#define Window_ICONIFIED 1L
#undef Window_MAXIMIZED_HORIZ
#define Window_MAXIMIZED_HORIZ 2L
#undef Window_MAXIMIZED_VERT
#define Window_MAXIMIZED_VERT 4L
#undef Window_MAXIMIZED_BOTH
#define Window_MAXIMIZED_BOTH 6L
#undef Window_serialVersionUID
#define Window_serialVersionUID 2673458971256075116i64
/*
 * Class:     Window
 * Method:    handleClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Window_handleClick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Window
 * Method:    findWhereToPaintOval
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_Window_findWhereToPaintOval
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Window
 * Method:    checkIfWIN
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Window_checkIfWIN
  (JNIEnv *, jobject);

/*
 * Class:     Window
 * Method:    getCurrentColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Window_getCurrentColor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
